type Project @table {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  domain: String!
  techStack: [String!]!
  image: String!
  description: String!
  createdAt: Timestamp! @default(expr: "request.time")
}

type User @table(key: "uid") {
  uid: String! @default(expr: "auth.uid")
  email: String! @unique
  displayName: String
}
